### ISSUE TITLE
Letting Others Open PRs on repo?

### ISSUE THREAD

**Issue by KhachDavid** [TURX/WISC-CS354-SP22-P4-Tester#1]
I appreciate this automated testing script you wrote. It would be amazing if you can leave the floor open for pull requests to improve it.

**Comment by TURX** [comment]
I think the pull request is always allowed.

**Comment by KhachDavid** [comment]
<img width="1196" alt="image" src="https://user-images.githubusercontent.com/65775837/161658965-c6b96cca-2871-421d-8110-43bc40270830.png">

Just tried to open a PR and it gave a 403. Maybe it is from my end, hmmm. Let me check further.

**Comment by TURX** [comment]
You should not directly push to this repo, but make a fork, and then open a pull request from that fork. That is how a pull request works.
